### ISSUE TITLE
Questions about job dependencies

### ISSUE THREAD

**Issue by wuvei** [google/cluster-data#21]
Hi, I want to ask about job dependencies in the 2019 trace.
In the "Collections and instances" section, the [doc](https://drive.google.com/file/d/10r6cnJ5cJ89fPWCgj7j4LtLBqYN9RiI9/view) mentioned
```
A common pattern is to run masters (controllers) and workers in separate jobs (e.g., this is used in MapReduce and similar systems). A worker job that has a master job as a parent​ will automatically be terminated when the ​parent​ exits, even if its workers are still running. A job can have multiple child jobs but only one ​parent​.

Another pattern is to run jobs in a pipeline (this doesn’t apply to alloc sets). If job A says that it should ​run after​ job B, then job A will only be scheduled (made READY) after job B successfully finishes. A job can list multiple jobs that it should ​run after,​ and will only be scheduled after all those jobs finish successfully. 
```
Could you provide a few examples of the second pattern?

For example, if a Spark program executed on Borg in the trace, would different stages be scheduled as separate jobs in pipeline? Or were they scheduled as tasks and their order was decided by an external scheduler?

**Comment by monnand** [comment]
As you quoted from the document, it already gives you an example. You can just replace MapReduce with Spark in the sentence, it's basically tells you what we are doing.

Here is some more details about the statement:

For data processing pipelines like MapReduce, Flume, spark or apache beam, etc. there will always two pieces of the pipeline: the manager and the workers. The workers, or usually referred to as worker pool, consists of multiple instances of the pipeline that can do arbitrary IO and computations (i.e. real work.) The manger monitors the worker pool and sends instructions to individual workers telling them what to do (e.g. read data, write data, run some function, etc.)

One could architect their pipeline so that the manager and the worker pool runs as two different jobs and let the worker pool depends on the manager, meaning, the worker pool will be killed once the manager finishes. This is just an easier way to manager the pipeline so that the manager won't need to worry about killing the worker pool. It just exit and the underlying system (in Google, it's Borg) could handle the kill properly.

Regarding to your questions:

> For example, if a Spark program executed on Borg in the trace, would different stages be scheduled as separate jobs in pipeline? Or were they scheduled as tasks and their order was decided by an external scheduler?

It has nothing to do with the stages inside the pipeline, although the pipeline itself could *choose* to put different stages into different jobs if they saw fit. But it's really a pattern internally.
